### ISSUE TITLE
[unstrip] Can't find default module

### ISSUE THREAD

**Issue by Oloshka** [dyninst/tools#12]
After building unstrip I try to learn it for some library but got error.
```
$ ./generate-learn-binary.bash ./musl.a
$ LD_LIBRARY_PATH=/opt/dyninst/lib/ ./unstrip -f learning-binaries/musl.a.bin -l
can't find default module
```
What am I doing wrong?

**Comment by wrwilliams** [comment]
Possibly nothing. We've changed some of the module internals since unstrip was last updated and I should go back and test it on libraries and see what needs fixing if anything.

**Comment by Oloshka** [comment]
Could you please tell me which dyninst release is relevant to unstrip current state?

**Comment by wrwilliams** [comment]
Dyninst 8.2 should work with unstrip (I think). But I'll take a look today now that I'm back in the office and see what's needed to get master/9.3 behaving.

**Comment by wrwilliams** [comment]
This was a trivial one and the fix is pushed to this repo; our default module now properly has the name of the binary, rather than DEFAULT_MODULE, and unstrip is updated to account for this.

**Comment by Oloshka** [comment]
Thank you!

**Comment by Ruturaj4** [comment]
I am getting the same issue:

Complete error message:

```
Could not open param info file: ./params.db
Database setup failed
can't find default module
```

When tested on ls:

```
Could not open param info file: ./params.db
Database setup failed
unstrip: /projects/zephyr/Ruturaj/dyninst/instructionAPI/src/InstructionDecoderImpl.C:76: static Dyninst::InstructionAPI::InstructionDecoderImpl::Ptr Dyninst::InstructionAPI::InstructionDecoderImpl::makeDecoderImpl(Dyninst::Architecture): Assertion `0' failed.
Aborted (core dumped)
```
