### ISSUE TITLE
virtual bool AstCallNode::initRegisters(codeGen&): Assertion `callee' failed

### ISSUE THREAD

**Issue by huangshiyou** [dyninst/tools#13]
When I tested the coverage tool on the given example, it reported the following error:

"virtual bool AstCallNode::initRegisters(codeGen&): Assertion `callee' failed."
Command I used:
./codeCoverage testcc testcc.inst

Any ideas about this error?

**Comment by stevenagy** [comment]
I'm getting the same issue! Any help would be much appreciated!

**Comment by kwonsoonhong** [comment]
Hi!
Are you resolve this problem??

**Comment by hainest** [comment]
When this issue was brought up in https://github.com/dyninst/dyninst/issues/442, the solution appears to be correctly setting `DYNINSTAPI_RT_LIB` in the environment. Please try that and let us know if the issue remains.

**Comment by stevenagy** [comment]
Yeah I've since resolved it! Thank you! :)
